"""empty message

Revision ID: 6284151b7527
Revises: 07dc44b2aa21
Create Date: 2020-08-23 08:33:02.653881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6284151b7527'
down_revision = '07dc44b2aa21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('zipcode', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'zipcode')
    # ### end Alembic commands ###
